sudo: required
dist: xenial
language: python
python:
  - '3.6'
  
services:
  - postgresql

branches:
  only:
    - staging

addons:
  firefox: latest

before install:
   - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
   - mkdir geckodriver
   - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
   - export PATH=$PATH:$PWD/geckodriver
   - geckodriver --version
   - export MOZ_HEADLESS=1

before_script:
  - psql -c "CREATE USER tetrew WITH PASSWORD 'test';" -U postgres
  - psql -U postgres -c "ALTER USER tetrew CREATEDB;"
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE=purBeurre_project.settings

script:
  - python3 manage.py test
