sudo: required
dist: xenial
language: python
python:
  - '3.6'
  
addons:
  firefox: "60.0"
  
services:
  - postgresql
  - xvfb

branches:
  only:
    - staging
    
before_install:
- sudo apt-get -qq update
- sudo apt-get clean
- sudo apt-get install dpkg
- sudo apt-get install dbus-x11
- export DISPLAY=:99.0
- export CHROME_BIN=/usr/bin/google-chrome
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo cp chromedriver /usr/bin
- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
- tar -xzf geckodriver-v0.24.0-linux64.tar.gz
- sudo cp geckodriver /usr/bin

before_script:
  - psql -c "CREATE USER tetrew WITH PASSWORD 'test';" -U postgres
  - psql -U postgres -c "ALTER USER tetrew CREATEDB;"
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE=purBeurre_project.settings

script:
  - python3 manage.py test
