language: python
python:
  - '3.6'

branches:
  only:
    - staging

before_script:
  - psql -c "CREATE USER tetrew WITH PASSWORD 'test';" -U postgres
  - psql -U postgres -c "ALTER USER tetrew CREATEDB;"
  - pip3 install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purBeurre_project.settings

script:
  - python3 manage.py test
