# Generated by Django 3.0.6 on 2020-10-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('substituteName', models.CharField(max_length=100)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
