# Generated by Django 3.0.6 on 2020-10-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitutesearch', '0001_initial'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='substituteName',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='userId',
        ),
        migrations.AddField(
            model_name='favorites',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='substitutesearch.Product'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='substitute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='substitutesearch.Product'),
        ),
    ]
