# Generated by Django 3.0.6 on 2020-10-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20201022_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='password',
        ),
    ]
